#!make

start-build-pipeline:	cleanup provision-jenkins-ssh-agent
	cd server-build && \
		docker compose up --build --force-recreate -d
	echo '========================'
	echo 'Jenkins Initial Password'
	echo '========================'
	cd server-build && \
		docker compose exec 17636-jenkins cat /var/jenkins_home/secrets/initialAdminPassword

provision-jenkins-ssh-agent:
	yes | ssh-keygen -q -N "" -f ./server-build/17636-jenkins-ssh-build-agent.key
	echo "# Do not manually modify this file. This file is generated by ../Makefile" \
		> ./server-build/.env.jenkins-ssh-build-agent
	echo "JENKINS_AGENT_SSH_PUBKEY=$$(cat ./server-build/17636-jenkins-ssh-build-agent.key.pub)" \
		>> ./server-build/.env.jenkins-ssh-build-agent

# TODO: Automatically generate a random number -> random hash for
# the pet clinic db password. Implement this after all core functionalities.

cleanup:
	cd server-build && \
	  docker compose down --remove-orphans || 1

cleanup-remove-images:
	docker images -aq --filter 'reference=soobinrho/17636-*' \
		| xargs docker image rm --force

.SILENT: start-build-pipeline
