#!make

start-build-pipeline:	clean \
											check-if-env-file-ready \
											provision-jenkins-ssh-agent \
											setup-env-file-jenkins \
											setup-env-file-jenkins-ssh-agent \
											setup-env-file-petclinic
	cd server-build && \
		docker compose up --build --force-recreate -d

check-if-env-file-ready:
	if [ ! -f ./.env ]; then \
	  echo '[ERROR] .env file does not exist. Please cp ./.env.example .env and populate the variables.'; \
		exit 1; \
	fi

provision-jenkins-ssh-agent:
	yes | ssh-keygen -q -N "" -f ./server-build/17636-jenkins-ssh-agent.key

setup-env-file-jenkins:
	echo "# Do not manually modify this file. This file is generated by ../Makefile" \
		> ./server-build/.env.jenkins
	grep '^JENKINS_URL_AND_PORT=' ./.env \
		>> ./server-build/.env.jenkins
	grep '^JENKINS_ADMIN_USER=' ./.env \
		>> ./server-build/.env.jenkins
	grep '^JENKINS_ADMIN_PASS=' ./.env \
		>> ./server-build/.env.jenkins
	echo "JENKINS_AGENT_SSH_PRIVATE_KEY=\"$$(cat ./server-build/17636-jenkins-ssh-agent.key)\"" \
		>> ./server-build/.env.jenkins

setup-env-file-jenkins-ssh-agent:
	echo "# Do not manually modify this file. This file is generated by ../Makefile" \
		> ./server-build/.env.jenkins-ssh-agent
	echo "JENKINS_AGENT_SSH_PUBKEY=$$(cat ./server-build/17636-jenkins-ssh-agent.key.pub)" \
		>> ./server-build/.env.jenkins-ssh-agent

setup-env-file-petclinic:
	echo "# Do not manually modify this file. This file is generated by ../Makefile" \
		> ./server-build/.env.petclinic
	grep '^POSTGRES_PASSWORD=' ./.env \
		>> ./server-build/.env.petclinic
	grep '^POSTGRES_PASS=' ./.env \
		>> ./server-build/.env.petclinic

logs:
	cd server-build && \
	  docker compose logs -f

reset:	clean clean-remove-volumes start-build-pipeline

clean:
	cd server-build && \
	  docker compose down --remove-orphans || 1

clean-remove-volumes:
	docker volume ls -q --filter 'name=17636-*' | xargs docker volume rm

clean-remove-images:
	docker images -aq --filter 'reference=soobinrho/17636-*' \
		| xargs docker image rm --force

test-sh-in-jenkins:
	cd server-build && \
		docker compose exec 17636-jenkins bash

test-sh-in-jenkins-ssh-agent:
	cd server-build && \
		docker compose exec 17636-jenkins-ssh-agent bash

test-sh-in-postgres:
	cd server-build && \
		docker compose exec 17636-postgres bash

.SILENT: start-build-pipeline \
	check-if-env-file-ready \
	provision-jenkins-ssh-agent \
	setup-env-file-jenkins \
	setup-env-file-jenkins-ssh-agent \
	setup-env-file-petclinic \
	logs \
	clean \
	clean-remove-volumes \
	clean-remove-images \
	test-sh-in-jenkins \
	test-sh-in-jenkins-ssh-agent \
	test-sh-in-postgres

