services:
  17636-petclinic:
    image: soobinrho/17636-petclinic:latest
    ports:
      - "80:8080"
    networks:
      - network-petclinic
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_PASS=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
      - POSTGRES_URL=jdbc:postgresql://17636-postgres/petclinic
    depends_on:
      17636-postgres:
        condition: service_healthy

  17636-postgres:
    image: postgres:18.4
    ports:
      - "5432:5432"
    networks:
      - network-petclinic
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - PGUSER=petclinic
      - POSTGRES_DB=petclinic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "petclinic", "-U", "petclinic"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  network-petclinic:
