---
- name: Export the pet clinic Docker image
  hosts: localhost
  connection: local
  tasks:
    - name: Export the pet clinic Docker image
      community.docker.docker_image_export:
        name: soobinrho/17636-pet-clinic:latest
        path: /tmp/docker_image_17636-pet-clinic.latest.tar

- name: Import the image and deploy it using Docker Compose
  hosts: server_prod
  become: true
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
  tasks:
    - name: Download the exported Docker image
      ansible.builtin.copy:
        path: /tmp/docker_image_17636-pet-clinic.latest.tar
        dest: /tmp/docker_image_17636-pet-clinic.latest.tar
        mode: '0644'

    - name: Import the pet clinic Docker image
      community.docker.docker_image_load:
        path: /tmp/docker_image_17636-pet-clinic.latest.tar

    - name: Cleanup
      ansible.builtin.file:
        path: /tmp/docker_image_17636-pet-clinic.latest.tar
        state: absent

    - name: Download the Docker Compose file
      ansible.builtin.git:
        repo: 'https://github.com/soobinrho/17636-devsecops-industry-best-practices.git'
        dest: /app
        version: main
        depth: 1

    - name: Deploy the pet clinic web app consisting of Spring and Postgres
      community.docker.docker_compose_v2:
        project_src: /app/server-prod
        state: present

