# Reference: http://<JENKINS_URL>/manage/configuration-as-code/reference
jenkins:
  systemMessage: "SCM: https://github.com/soobinrho/17636-devsecops-industry-best-practices"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USER}
          password: ${JENKINS_ADMIN_PASS}
  nodes:
    - permanent:
        nodeName: "17636-jenkins-ssh-agent"
        nodeDescription: "Provisioned by Docker Compose. This is Linux box running an SSH server."
        labelString: "linux ssh-agent"
        numExecutors: 1
        remoteFS: "/home/jenkins/agent"
        mode: NORMAL
        launcher:
          ssh:
            credentialsId: "17636-jenkins-ssh-agent-key"
            host: "17636-jenkins-ssh-agent"
            port: 2222
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "17636-jenkins-ssh-agent-key"
              passphrase: ""
              username: "jenkins"
              description: "SSH private key for the Jenkins agent."
              privateKeySource:
                directEntry:
                  privateKey: ${JENKINS_AGENT_SSH_PRIVATE_KEY}
          - string:
              scope: GLOBAL
              id: "sonarqube-token"
              description: "Token generated by SonarQube."
              secret: ${SONARQUBE_TOKEN}
          - basicSSHUserPrivateKey:
              description: "Edit the private key value before use (Generate a SSH key pair and paste the private key here)."
              id: "17636-prod-ssh-key"
              privateKeySource:
                directEntry:
                  privateKey: ""
              scope: GLOBAL
              username: "jenkins"
          - string:
              scope: GLOBAL
              id: "17636-prod-ansible-inventory"
              description: "Edit this before use. This will be used in 'ansible-playbook -i <HERE>'."
              secret: ""

unclassified:
  location:
    url: ${JENKINS_URL_AND_PORT}
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - credentialsId: "sonarqube-token"
      name: "sonarqube"
      serverUrl: "http://17636-sonarqube:9000"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
  prometheusConfiguration:
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 5
    path: "prometheus"
    useAuthenticatedEndpoint: false

# Reference: http://localhost:8080/manage/configuration-as-code/viewExport
tool:
  sonarRunnerInstallation:
    installations:
      - name: "sonarqube"
        properties:
          - installSource:
              installers:
                - sonarRunnerInstaller:
                    id: "8.1.0.6389"

jobs:
  - script: |
      pipelineJob('17636-petclinic') {
        description('SCM: https://github.com/soobinrho/17636-devsecops-industry-best-practices')
        logRotator {
          numToKeep(10)
        }
        properties {
          // Reference: https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration#migrating-to-172
          pipelineTriggers {
            triggers {
              cron {
                spec('* * * * *')
              }
            }
          }
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/soobinrho/17636-devsecops-industry-best-practices')
                }
                branches('*/main')
                extensions {
                  submoduleOptions {
                    recursive(true)
                  }
                }
              }
            }
            scriptPath('./server-build/Jenkinsfile') 
          }
        }
      }
