---
- name: Depoy the Petclinic Web App
  hosts: all
  tasks:
    - name: Checkout the repository
      ansible.builtin.git:
        repo: 'https://github.com/soobinrho/17636-devsecops-industry-best-practices.git'
        dest: /home/jenkins/17636
        version: "{{ git_hash }}"
        recursive: false
        force: true

    - name: Checkout the git submodule for petclinic
      ansible.builtin.shell:
        cmd: "git submodule update --init --recursive"
        chdir: /home/jenkins/17636

    - name: Stop the current instance of the petclinic web app
      ansible.builtin.shell:
        cmd: "./mvnw spring-boot:stop"
        chdir: /home/jenkins/17636/spring-petclinic

    - name: Deploy petclinic
      ansible.builtin.shell:
        cmd: "nohup ./mvnw spring-boot:run > petclinic.log 2>&1 &"
        chdir: /home/jenkins/17636/spring-petclinic
      async: 10
      poll: 0
