---
- name: Depoy the Petclinic Web App
  hosts: all
  tasks:
    - name: Checkout the repository
      ansible.builtin.git:
        repo: 'https://github.com/soobinrho/17636-devsecops-industry-best-practices.git'
        dest: /home/jenkins/17636
        version: "{{ git_hash }}"
        recursive: false

    - name: Checkout the git submodule for petclinic
      ansible.builtin.command:
        cmd: git submodule update --init --recursive
        chdir: /home/jenkins/17636

    - name: Deploy the petclinic web app
      ansible.builtin.shell: >
        cd /home/jenkins/17636/spring-petclinic && \
        ./mvnw spring-boot:stop && \
        ./mvnw spring-boot:start
      args:
        executable: /bin/bash
