services:
  17636-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: soobinrho/17636-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-jenkins:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/jenkins.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    env_file:
      - ./.env.jenkins
    healthcheck:
      test: ["CMD-SHELL", "curl --silent http://localhost:8080/login | grep -q 'Jenkins' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 50
      start_period: 5s

  17636-jenkins-ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-ssh-agent
    image: soobinrho/17636-jenkins-ssh-agent
    ports:
      - "22:22"
    networks:
      - network-jenkins
    volumes:
      - ./17636-playbook.yaml:/home/jenkins/agent/workspace/17636-playbook.yaml
      - ./.env.petclinic:/home/jenkins/agent/workspace/.env.petclinic
    env_file:
      - ./.env.jenkins-ssh-agent
      - ./.env.petclinic

  17636-sonarqube:
    image: sonarqube:26.7.0.124771-community
    ports:
      - "9000:9000"
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-sonarqube-data:/opt/sonarqube/data
      - 17636-volume-sonarqube-extensions:/opt/sonarqube/extensions
      - 17636-volume-sonarqube-logs:/opt/sonarqube/logs
    # Reference: https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
    tmpfs:
      - /tmp:size=256M,mode=1777
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000/api/system/status | grep -q -e '\"status\":\"UP\"'"]
      interval: 2s
      timeout: 5s
      retries: 50
      start_period: 2s

  # Reference: https://www.zaproxy.org/docs/docker/about/
  17636-zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    user: zap
    ports:
      - "8081:8080"
      - "8090:8090"
    command: zap-webswing.sh
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-zap:/zap/wrk

  17636-prometheus:
    image: prom/prometheus:v3
    ports:
      - "9090:9090"
    networks:
      - network-jenkins
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - 17636-volume-prometheus:/prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy"]
      interval: 2s
      timeout: 5s
      retries: 50
      start_period: 2s
    depends_on:
      17636-jenkins:
        condition: service_healthy

  17636-grafana:
    image: grafana/grafana:11.6
    ports:
      - "3000:3000"
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./.env.grafana
    depends_on:
      17636-prometheus:
        condition: service_healthy

  # This is required for monitoring the system CPU and memory usage.
  17636-prometheus-node-exporter:
    image: prom/node-exporter:v1
    ports:
      - "9100:9100"
    networks:
      - network-jenkins
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'

networks:
  network-jenkins:

volumes:
  17636-volume-jenkins:
  17636-volume-sonarqube-data:
  17636-volume-sonarqube-extensions:
  17636-volume-sonarqube-logs:
  17636-volume-zap:
  17636-volume-prometheus:
  17636-volume-grafana:
