services:
  17636-jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - network-jenkins
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - volume-jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    # Required because "permission denied while trying to connect to the docker API."
    privileged: true
    user: root

  17636-sonarqube:
    image: sonarqube:26.7.0.124771-community
    ports:
      - "9000:9000"
    networks:
      - network-jenkins
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - volume-sonarqube-data:/opt/sonarqube/data
      - volume-sonarqube-extensions:/opt/sonarqube/extensions
      - volume-sonarqube-logs:/opt/sonarqube/logs

  17636-prometheus:
    image: prom/prometheus:v3
    ports:
      - "9001:9000"
    networks:
      - network-jenkins
    depends_on:
      17636-jenkins:
        condition: service_started

  17636-grafana:
    image: grafana/grafana:11.6.16
    ports:
      - "3000:3000"
    networks:
      - network-jenkins
    depends_on:
      17636-prometheus:
        condition: service_started

  # The pet clinic and the database are only required for the prod server,
  # and are not required to run here, since Jenkins will clone the repo
  # and run the tests and build scripts in the bulid server.

  # Nevertheless, these two are included here because the assignment's
  # requirement specifically calls for it.
  17636-petclinic:
    image: soobinrho/17636-petclinic:latest
    ports:
      - "80:8080"
    networks:
      - network-petclinic
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_PASS=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
      - POSTGRES_URL=jdbc:postgresql://17636-postgres/petclinic
    depends_on:
      17636-postgres:
        condition: service_healthy

  17636-postgres:
    image: postgres:18.4
    ports:
      - "5432:5432"
    networks:
      - network-petclinic
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - PGUSER=petclinic
      - POSTGRES_DB=petclinic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "petclinic", "-U", "petclinic"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  network-jenkins:
  network-petclinic:

volumes:
  volume-jenkins:
  volume-sonarqube-data:
  volume-sonarqube-extensions:
  volume-sonarqube-logs:
