services:
  17636-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-jenkins:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/jenkins.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    env_file:
      - ./.env.jenkins

  17636-jenkins-ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-ssh-agent
    ports:
      - "22:22"
    networks:
      - network-jenkins
    env_file:
      - ./.env.jenkins-ssh-agent
      - ./.env.petclinic

  17636-sonarqube:
    image: sonarqube:26.7.0.124771-community
    ports:
      - "9000:9000"
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-sonarqube-data:/opt/sonarqube/data
      - 17636-volume-sonarqube-extensions:/opt/sonarqube/extensions
      - 17636-volume-sonarqube-logs:/opt/sonarqube/logs
    # Reference: https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
    tmpfs:
      - /tmp:size=256M,mode=1777
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000/api/system/status | grep -q -e '\"status\":\"UP\"'"]
      interval: 2s
      timeout: 5s
      retries: 50
      start_period: 5s

  # Reference: https://www.zaproxy.org/docs/docker/about/
  17636-zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    user: zap
    ports:
      - "8081:8080"
      - "8090:8090"
    command: zap-webswing.sh
    networks:
      - network-jenkins
    volumes:
      - 17636-volume-zap:/zap/wrk
    # environment:
    #   - ZAP_WEBSWING_OPTS="-host 0.0.0.0 -port 8080"

  # 17636-prometheus:
  #   image: prom/prometheus:v3
  #   ports:
  #     - "9001:9000"
  #   networks:
  #     - network-jenkins
  #   depends_on:
  #     17636-jenkins:
  #       condition: service_started
  #
  # 17636-grafana:
  #   image: grafana/grafana:11.6.16
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - network-jenkins
  #   depends_on:
  #     17636-prometheus:
  #       condition: service_started

networks:
  network-jenkins:

volumes:
  17636-volume-jenkins:
  17636-volume-sonarqube-data:
  17636-volume-sonarqube-extensions:
  17636-volume-sonarqube-logs:
  17636-volume-zap:
