FROM jenkins/jenkins:lts-jdk25

# Installing via apt requires root.
# Source: https://github.com/jenkinsci/docker#installing-more-tools
# USER root
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     ca-certificates \
#     curl \
#     gnupg \
#     && rm -rf /var/lib/apt/lists/*
# RUN install -m 0755 -d /etc/apt/keyrings && \
#     curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
#     chmod a+r /etc/apt/keyrings/docker.gpg
# RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
#     $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
# RUN apt-get update && apt-get install -y --no-install-recommends docker-ce-cli && rm -rf /var/lib/apt/lists/*
# USER jenkins

# How to manage Jenkins plugins:
#   https://www.jenkins.io/blog/2023/06/20/remove-outdated-plugins-while-using-docker/
COPY --chown=jenkins:jenkins ./17636-jenkins-plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli --plugin-file=/usr/share/jenkins/plugins.txt
