FROM jenkins/ssh-agent:latest-alpine-jdk21
RUN apk update && \
    apk add --no-cache \
    docker \
    ansible \
    python3 \
    firefox \
    zaproxy && \
    zaproxy -cmd -addoninstall report && \
    zaproxy -cmd -addoninstall client && \
    zaproxy -cmd -addoninstall automation && \
    zaproxy -cmd -addoninstall ptk
RUN mkdir --parent /home/jenkins/agent/workspace && \
    chown -R jenkins:jenkins /home/jenkins/agent/workspace
COPY --chown=jenkins:jenkins ./zap-owasp-penetration-testing-kit.yaml /home/jenkins/agent/workspace/
