pipeline {
    agent any
    stages {
        stage('Static Analysis') {
            environment {
                scannerHome = tool 'sonarqube';
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh 'pwd && whoami'
                    sh 'ls -la'
                    sh 'env'
                    sh 'uname -a'
                    sh 'cat /etc/os-release'
                    sh 'hostname'
                    sh 'route'
                }
                withSonarQubeEnv(installationName: 'sonarqube') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('Build') {
            steps {
                sh 'echo building...'
            }
        }
        stage('Vulnerability Scanning and Penetrating Testing') {
            steps {
                sh 'echo security testing...'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo deploying...'
            }
        }
    }
    post {
        success {
            echo '[INFO] Successful!'
        }
        failure {
            echo '[ERROR] Pipeline has failed!'
        }
    }
}
