pipeline {
    agent {
      label 'linux && ssh-agent'
    }
    stages {
        stage('Static Analysis') {
            // environment {
            //     scannerHome = tool 'sonarqube';
            // }
            steps {
                sh 'echo DEFAULT NODE'
                sh 'env'
                sh 'hostname'
                sh 'pwd && whoami'
                sh 'uname -a'
                // withSonarQubeEnv(installationName: 'sonarqube') {
                //     sh "${scannerHome}/bin/sonar-scanner"
                // }
            }
        }
        stage('Build') {
            steps {
                sh 'echo building...'
            }
        }
        stage('Vulnerability Scanning and Penetrating Testing') {
            steps {
                sh 'echo security testing...'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo deploying...'
            }
        }
    }
    post {
        success {
            echo '[INFO] Successful!'
        }
        failure {
            echo '[ERROR] Pipeline has failed!'
        }
    }
}
